### ISSUE TITLE
PHP 5.3.3

### ISSUE THREAD

**Issue by johnny5th** [loduis/TeamWorkPmPhpApi#21]
Is there any way to get this script to run on PHP 5.3.3? I see in the composer.json file it requires 5.4 (haven't figured out how to use composer to generate the autoloader yet)

**Comment by loduis** [comment]
Not in this point.

**Comment by johnny5th** [comment]
I went through and replaced all the 5.4 arrays with 5.3 type arrays, and the implementation that I need works. Would you like a pull request?

**Comment by simonschaufi** [comment]
php 5.3 is outdated by now.
