### ISSUE TITLE
Update to repo Name

### ISSUE THREAD

**Issue by holly-mcgill** [loduis/TeamWorkPmPhpApi#41]
Hey guys!

Holly here from Teamwork.com. I was hoping to you could please update the name on the read me and title for this?
- TeamworkPM to Teamwork.com?

We would greatly appreciate it :)

Have a great day,
Holly

**Comment by simonschaufi** [comment]
@loduis could you please rename the repository name as I don't have the permission to or give me the permission to do so.

**Comment by loduis** [comment]
Hi @simonschaufi What name do you want me to place?

**Comment by simonschaufi** [comment]
I would suggest `Teamwork.comPhpApi`

**Comment by loduis** [comment]
I think is best "teamwork-project-management"

You can see the project of teamwork.

https://www.teamwork.com/

**Comment by simonschaufi** [comment]
Well, "Teamwork.com" is the official name so imho "com" should also be part of it.

**Comment by simonschaufi** [comment]
Thank you. Could you also please update the description below the repo name in english?

**Comment by simonschaufi** [comment]
PHP API for Teamwork.com

and delete all the rest.
